### ISSUE TITLE
Too much memory usage with a big file

### ISSUE THREAD

**Issue by L-Yvelin** [luejerry/html-mangareader#18]
When merging a whole manga in a single file, the app uses the whole computer's memory
(Maybe loading the images in a certain buffer size, and unloading them when they go past it)

**Comment by luejerry** [comment]
Hi, I am testing an unreleased version of the app that should decrease memory usage. I don't know what kind of files you are trying to open with it, so would you mind giving this prerelease build a try and let me know how it works for your use case?

[mangareader-win64-2.1.0.zip](https://github.com/luejerry/html-mangareader/files/9561917/mangareader-win64-2.1.0.zip)

**Comment by L-Yvelin** [comment]
Hi Jerry, your fix seems to be working really well. There's a little lag at the beginning or when you jump somewhere else, but that's probably just the images. Thank you very much!
For info, the file I used was about 5000 pages CBZ file.

**Comment by luejerry** [comment]
Glad it worked ok! The lag when jumping to a page is a natural consequence of dynamically loading/unloading images, how bad it is will depend on your CPU/storage speed. Lag at startup is likely because the new app version does some background preprocessing for thumbnails to have them work with the dynamic image loading (for 5000 pages this can take quite a while), this can be sped up by disabling the right side navbar in the latest version.
