### ISSUE TITLE
Is there a way to get it working on my phone?

### ISSUE THREAD

**Issue by Dividedby0KSJ** [luejerry/html-mangareader#7]
For example, running the newly created web-page on the host PC and allowing my iPad to connect to it.
or some other method. because this is the only application that does the things I need with CBZ files (the Infinite scroll with Collapse spacing)

**Comment by luejerry** [comment]
Unfortunately this is not possible at the time. Currently the app does not run any kind of background server process; rather it generates all the static web assets when opened and "serves" them to the browser via a `file://` url directly from the local filesystem. Which means they are only available on the local machine.

I've been mulling over converting the app over to using a background server, in order to get around a number of limitations with `file://` urls that prevent me from implementing certain features such as requested in #5, and also what you've requested. However this would require a significant re-architecting of the app so I can't promise it'll be here anytime soon, but it is certainly on the long-term roadmap.

**Comment by Dividedby0KSJ** [comment]
Well, its good to hare that it's latest on the long-term roadmap, that app itself in its current state is still really good for a tablet running windows or a regular PC. I will definitely still be using this until then.

![thumbs up anime](https://clip.cookdiary.net/sites/default/files/wallpaper/anime-clipart/484512/anime-clipart-thumbs-484512-3840283.jpg)

**Comment by luejerry** [comment]
Unfortunately I've decided to drop any plans for this feature because after further research I believe the necessary changes are not compatible with the original goal of being a lightweight offline reader. For anyone who might be looking for this functionality, I would recommend something like [Mango](https://github.com/getmango/Mango) instead.
